CREATE SCHEMA MASTER.STUDYBUDDY;

CREATE TABLE STUDYBUDDY.Users (
    user_id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    username NVARCHAR(50) NOT NULL,
    password NVARCHAR(100) NOT NULL,
    email NVARCHAR(100),
    school NVARCHAR(100),
    role NVARCHAR(100) NOT NULL
);